# Generated by Django 6.0.5 on 2026-05-22 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_alter_contact_name_alter_contact_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='icon_class',
            new_name='class_name',
        ),
    ]
